### ISSUE TITLE
fix pursuit url

### ISSUE THREAD

**Issue by safareli** [slamdata/purescript-sql-squared#32]
This is pursuit url https://pursuit.purescript.org/packages/purescript-sqlsquare
This is installation instruction in readme `bower install purescript-sqlsquare`

```sh
$ bower i --save purescript-sqlsquare
bower ENOTFOUND     Package purescript-sqlsquare not found
$ bower i --save purescript-sql-squared
bower cached        https://github.com/slamdata/purescript-sql-squared.git#0.8.2
bower validate      0.8.2 against https://github.com/slamdata/purescript-sql-squared.git#*
bower install       purescript-sqlsquare#0.8.2
....
```

We should fix pursuit url + update readme or fix url of this repo.

**Comment by safareli** [comment]
also name in bower.json is `purescript-sqlsquare`

**Comment by garyb** [comment]
The repo used to be called `purescript-sqlsquare`, so we should update all the other stuff

**Comment by safareli** [comment]
reopening as pursuit link is not working (`bower install` works fine)

**Comment by safareli** [comment]
https://pursuit.purescript.org/packages/purescript-sql-squared is working
